// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: namenode.proto

#include "namenode.pb.h"
#include "namenode.grpc.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/channel_interface.h>
#include <grpcpp/impl/codegen/client_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/method_handler_impl.h>
#include <grpcpp/impl/codegen/rpc_service_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/sync_stream.h>
namespace namenodeproto {

static const char* NameNodeSer_method_names[] = {
  "/namenodeproto.NameNodeSer/SayHello",
};

std::unique_ptr< NameNodeSer::Stub> NameNodeSer::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< NameNodeSer::Stub> stub(new NameNodeSer::Stub(channel));
  return stub;
}

NameNodeSer::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel)
  : channel_(channel), rpcmethod_SayHello_(NameNodeSer_method_names[0], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status NameNodeSer::Stub::SayHello(::grpc::ClientContext* context, const ::namenodeproto::HelloRequest& request, ::namenodeproto::HelloReply* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_SayHello_, context, request, response);
}

void NameNodeSer::Stub::experimental_async::SayHello(::grpc::ClientContext* context, const ::namenodeproto::HelloRequest* request, ::namenodeproto::HelloReply* response, std::function<void(::grpc::Status)> f) {
  return ::grpc::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_SayHello_, context, request, response, std::move(f));
}

void NameNodeSer::Stub::experimental_async::SayHello(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::namenodeproto::HelloReply* response, std::function<void(::grpc::Status)> f) {
  return ::grpc::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_SayHello_, context, request, response, std::move(f));
}

::grpc::ClientAsyncResponseReader< ::namenodeproto::HelloReply>* NameNodeSer::Stub::AsyncSayHelloRaw(::grpc::ClientContext* context, const ::namenodeproto::HelloRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderFactory< ::namenodeproto::HelloReply>::Create(channel_.get(), cq, rpcmethod_SayHello_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::namenodeproto::HelloReply>* NameNodeSer::Stub::PrepareAsyncSayHelloRaw(::grpc::ClientContext* context, const ::namenodeproto::HelloRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderFactory< ::namenodeproto::HelloReply>::Create(channel_.get(), cq, rpcmethod_SayHello_, context, request, false);
}

NameNodeSer::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      NameNodeSer_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< NameNodeSer::Service, ::namenodeproto::HelloRequest, ::namenodeproto::HelloReply>(
          std::mem_fn(&NameNodeSer::Service::SayHello), this)));
}

NameNodeSer::Service::~Service() {
}

::grpc::Status NameNodeSer::Service::SayHello(::grpc::ServerContext* context, const ::namenodeproto::HelloRequest* request, ::namenodeproto::HelloReply* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace namenodeproto

